{% set version = "2.2.2" %}
{% set name = "ratpoints" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.mathe2.uni-bayreuth.de/stoll/programs/{{ name }}-{{ version }}.tar.gz
  sha256: d80e1522190a1e122f7b2de2efc25efaac907f55f37635d8daddd0d18aaffd93
  patches:
    # remove nested functions to build with clang
    # from https://github.com/sagemath/sage/commit/4889e9c61580b1e894e67505ca2bfb4da9024712
    - patches/sturm_and_rp_private.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - make
  host:
    - gmp
  run:
    - gmp

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a

about:
  home: http://www.mathe2.uni-bayreuth.de/stoll/programs/index.html
  license: GPLv2+
  license_file: {{ SRC_DIR }}/gpl-2.0.txt
  summary: Ratpoints - a program that uses an optimized quadratic sieve algorithm in order to find rational points on hyperelliptic curves
  doc_url: http://www.mathe2.uni-bayreuth.de/stoll/programs/ratpoints-doc.pdf

extra:
  recipe-maintainers:
    - isuruf
