appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: phZRVKsmvY/UYmI7KtQGqphvwnG3i2+VJcF580aTNfb8Vut5jUDWMXunbD6YTTwu1PvGIwhIlMEzsldg/auoIFXfuG2jwu64UX1aeJdDd5Xf3QrEA0BEQ8t2sULZA0A11vfAltaPxixqFlshjEQWkSv23WNCuXI736PKN56hP0AqLI5TpgdLgDmmCocDNwrqJpAuuxKOcDydGvzZc3p/W6RkNRuBcqMFYDwVtpGk7Jh+XhnyOCbILRVY+3S7PWBB+p/WXe361ECuq/NflcWvDYiHwKkgp0JhXz2axRcEzb3x2DlztitJGllqjuZ1eRglCp4kotLktX20393PioAf7mGuBK1CUwJraoU/NdwMgBuZQrBaFZ3pPjb4S1xdX3xENUeyj8XjoOhCzstL43FRDLJ9fb+SMa1hIX/lXPN9/FrJDoO9QINU3uRby+KnHWzbPjXfjJYq6ouySHoX/kYmtSFDoNBIaWTdnQkAcdKzYLbZbMK3VtFCMTP23i0H9Mb4XQ1BoG4SS/o5j/oOMw9+EZCBN8DuCvwe2pP0wl0qsDS+LC7tDrOOYb96JxzA3uglrIec0mu07dlM1+/mboQQgYdTjC4BRKpzadgJb7qxoLkTbp44z7xqqDEKewhnKQf/yYa8ioPiV8Xsffk7zps8wwHE10ubt8T3twVs9uSp7pM=}
conda_forge_output_validation: false
