travis:
  secure:
    BINSTAR_TOKEN: gS30LZA+Gm66UVPlqNcckKjYCICaPDuP7Ed4ddTnJM8I2VuhbqHNIrChRIzk8FBztX0nZhRmvw5xE/qokVa7Hx9WeZVAHKWncywrjg5ERGTHCyetBXC1kZM0oXjv5mdwXLgksceGBL3dX0QxbBPkBoC2bMSfPG5ObHdVqiLS0ZhzasILKXUyCWUlWICOf8c+q93khPcD4gsvQcefBBgFKdPkBVha4JHTYzdBaOWaXoiM/X60d6Zm9PJ09HDv9SLdCzFl4emWWLx7gjtKw58dk6vZXO8l1nPfxiRhXW/NYEW017GLTC1Rh9zGz2+HrQmLj226I3SYIS7A2/LmtR3MIjcxzAkDIQtkfqAkswjmok0/3t0Cyr0MUHX1A5mhmvTOLlFSjZAnVHh3aFuCCjwE7f44zKVOjkxlX92JqjY83+WxToBSdfG0ykaP5xfm6FAvbgdc8B5ekhwSa/RdAfUHVvZ+sc1Ujs1TXeoFCuds+dxTu7glnMuoL1OhBW/UTod2YhA6EGmE47A6rcaGrZrd/85BVEMiDWRaT5KlsnONsJSvS+QyLaI6Xt53dEXDxAgchT5nNpHvGh2WXZSKv2aS513Tu3r8Do3GW79L7m/aFd72a6gA5hzYk3ajGj/l7HGeu4Gi/gg0Dsd0826KZjzvqBJhmgc2MkZjQgsbha3nqDk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
